### ISSUE TITLE
You can take a look at this

### ISSUE THREAD

**Issue by 1061127386** [Productivix/testRnBundleUpdate#1]
shm-open/code-push-server: CodePush service is an app hot update service which is compatible with react-native-code-push and other CodePush clients
https://github.com/shm-open/code-push-server

**Comment by Productivix** [comment]
thanks a lot , yes it seems to answer my seach. I will test that very soon ! 👍

**Comment by Productivix** [comment]
yes , I will close this project for hi, I will study the existing project : https://github.com/shm-open/code-push-server
